version: "3.8"
services:
  vue:
    image: registry.gitlab.com/serhii.leichenko/sellpoint-vue.js:latest
    restart: on-failure
    container_name: vue_sellpoint
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network: { }
