version: "3.8"
services:
  web:
    image: registry.gitlab.com/petro.sodel/sellpoint:latest
    container_name: web_sellpoint
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - /var/www/sellpoint/config/.env

  vue:
    image: registry.gitlab.com/serhii.leichenko/sellpoint-vue.js:latest
    restart: on-failure
    container_name: vue_sellpoint
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    restart: on-failure
    container_name: nginx_sellpoint
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
      - vue

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email admin@sellpoint.com.ua --agree-tos --no-eff-email --force-renewal -d sellpoint.com.ua


  redis:
    image: redis:latest
    container_name: redis_sellpoint
    ports:
      - "6379:6379"


  rabbit:
    image: rabbitmq:latest
    container_name: rabbit_sellpoint
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/


  celery:
    container_name: celery_sellpoint
    build: ./
    command: celery -A config worker -l info
    depends_on:
      - web
      - rabbit


  celery-beat:
    container_name: celery_beat_sellpoint
    build: ./
    command: celery -A config beat -l info
    depends_on:
      - web
      - redis

  flower:
    image: mher/flower
    command:  celery flower -A config --port=5555 --broker=redis://redis:6379
    ports:
      - "5555:5555"
    depends_on:
      - web
      - celery


volumes:
  certbot-etc:
  certbot-var:
  web-root:
  postgres_data:
  static_volume:
  celery_volume:
  celery_beat_volume:
  letsencrypt:
